name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    # Avoid forks to perform this job.
    if: github.repository_owner == 'moodlehq'
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Extract release notes from changelog
        id: extract-release-notes
        uses: yashanand1910/standard-release-notes@v1.5.0
        with:
          changelog_path: CHANGELOG.md
          version: ${{ github.ref }}

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          body: |
            ${{ steps.extract-release-notes.outputs.release_notes }}
